[window]
padding = { x = 4, y = 4 }
[font]
normal = { family = "Iosevka", style = "Regular" }
bold = { family = "Iosevka", style = "ExtraBold" }
italic = { family = "Iosevka", style = "Italic" }
bold_italic = { family = "Iosevka", style = "Bold Italic" }
[colors.primary]
background = "#101010"
